CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "RoleId" integer NOT NULL,
    "IsActive" boolean,
    "CreatedAt" timestamp with time zone,
    "PhoneNumber" text NOT NULL,
    "IsTwoFactorEnabled" boolean NOT NULL,
    "RefreshToken" text NOT NULL,
    "RefreshTokenExpiryTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserLogins" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "LoginTime" timestamp with time zone,
    "IpAddress" text,
    "IsSuccess" boolean NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserOtps" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "OtpCode" text NOT NULL,
    "ExpiryTime" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    CONSTRAINT "PK_UserOtps" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserOtps_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");

CREATE INDEX "IX_UserOtps_UserId" ON "UserOtps" ("UserId");

CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627041205_InitialCreate', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Users" ALTER COLUMN "RefreshTokenExpiryTime" TYPE timestamp without time zone;

ALTER TABLE "Users" ALTER COLUMN "CreatedAt" TYPE timestamp without time zone;

ALTER TABLE "UserOtps" ALTER COLUMN "ExpiryTime" TYPE timestamp without time zone;

ALTER TABLE "UserLogins" ALTER COLUMN "LoginTime" TYPE timestamp without time zone;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627052800_NewChanges', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "GymReports" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportName" text NOT NULL,
    "PaymentType" text NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_GymReports" PRIMARY KEY ("Id")
);

CREATE TABLE "GymReportRows" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GymReportId" integer NOT NULL,
    "CustomerName" text NOT NULL,
    "IsCustomerMember" boolean NOT NULL,
    "DateOfEnrollment" timestamp without time zone NOT NULL,
    "MembershipFee" numeric NOT NULL,
    "ContractDuration" text NOT NULL,
    "MonthlyPayment" numeric NOT NULL,
    "IncludePersonalTrainer" boolean NOT NULL,
    "PersonalTrainerPackage" text,
    "PaymentOption" text NOT NULL,
    "AmountToPay" numeric NOT NULL,
    CONSTRAINT "PK_GymReportRows" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GymReportRows_GymReports_GymReportId" FOREIGN KEY ("GymReportId") REFERENCES "GymReports" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_GymReportRows_GymReportId" ON "GymReportRows" ("GymReportId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627055259_AddGymReportTables', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "GymReportRows" ADD "OnlinePaymentMethod" text;

ALTER TABLE "GymReportRows" ADD "ReferenceNumber" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627060146_AddOnlinePaymentFields', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "GymReportRows" ADD "DailyPass" numeric;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627061936_AddDailyPassColumn', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "GymReportRows" ALTER COLUMN "DateOfEnrollment" TYPE date;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627145703_UpdateDateColumnDataType', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "GymReportRows" ALTER COLUMN "DateOfEnrollment" DROP NOT NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260627151743_ChangeDateOfEnrollmentColumnToNullable', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "ContractDuration" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ContractDuration" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_ContractDuration" PRIMARY KEY ("Id")
);

CREATE TABLE "Package" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Package" text NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Package" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260628005929_AddPackageAndContractDurationTable', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "Package" ADD "Price" numeric NOT NULL DEFAULT 0.0;

ALTER TABLE "ContractDuration" ADD "MonthlyPayment" numeric NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260628010504_AddAdditionalColumnsForPackageAndContractDurationTable', '10.0.9');

COMMIT;

START TRANSACTION;
CREATE TABLE "GymExpenses" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReportName" text NOT NULL,
    "Payroll" numeric NOT NULL,
    "OnlinePayment" numeric,
    "Electricity" numeric NOT NULL,
    "Water" numeric NOT NULL,
    "OtherUtilities" numeric NOT NULL,
    "TotalExpenses" numeric NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_GymExpenses" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260703132641_AddGymExpensesTable', '10.0.9');

COMMIT;

